name: Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:

    security:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout
                uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
                with:
                    fetch-depth: 0

            -   name: TruffleHog OSS
                uses: https://github.com/trufflesecurity/trufflehog@4dd8831c5f12599465d4d45c3c447b4018a34c85 # v3.97.9
                with:
                    extra_args: --results=verified,unknown --trust-local-git-config

    build:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout
                uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
                with:
                    fetch-depth: 0

            -   name: install graphicsmagick
                run: |
                    sudo apt-get update
                    sudo apt-get install -y graphicsmagick

            -   uses: ./.forgejo/actions/dart-sass

            -   name: enable Corepack
                shell: bash
                run: corepack enable

            -   name: setup node
                uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
                with:
                    node-version-file: '.nvmrc'
                    cache: 'yarn'
                    cache-dependency-path: yarn.lock

            -   name: yarn install
                shell: bash
                run: yarn install --immutable

            -   name: build assets
                shell: bash
                run: yarn run gulp
